
  name: lmntal-slim
  version: git # just for humans, typically '1.2+git' or '1.3.2'
  summary: SLIM - Slim LMNtal Imprementation # 79 char long summary
  description: |
    SLIM is the de-facto standard runtime of 
    a hierarchical graph rewriting language, LMNtal,
    and also has powerful features of model checkers.

  base: core18

  grade: stable # must be 'stable' to release into candidate/stable channels
  confinement: strict # use 'strict' once you have the right plugs and slots

  parts:
    build:
      # See 'snapcraft plugins'
      plugin: autotools
      source: https://github.com/lmntal/slim
      source-type: git
      build-packages:
        - g++
        - make
        - automake
        - autoconf
        - flex
        - bison
        - ruby
        - libtool
        - cunit
  
  apps:
    lmntal-slim:
      command: bin/slim
